name: json_api_annotation
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/breadkey/dart-json-api-generator

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
